@E_Commerce_API_HostAddress = https://localhost:44379

GET {{E_Commerce_API_HostAddress}}/api/weatherforecast/
Accept: application/json

###

GET {{E_Commerce_API_HostAddress}}/api/Products/Brand
Accept: application/json
